name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@2.7.0
        with:
          php-version: '7.4'
          tools: phpunit
          extension: mbstring, intl, simplexml, dom,
          ini-values: post_max_size=256M, short_open_tag=On
          coverage: xdebug
          pecl: false

      - name: Mark workspace as safe
        run: git config --global --add safe.directory /github/workspace

      - uses: php-actions/composer@v1
          
      - name: Run tests
        run: phpunit -c tests/configuration.xml
